### ISSUE TITLE
Have you considered adapting it for Windows and the web?

### ISSUE THREAD

**Issue by ShareZore** [fa-fifi/keycloak_wrapper#46]
Have you considered adapting it for Windows and the web? Is there a timeline for that?

**Comment by fa-fifi** [comment]
I did have that consideration before, but it would cost a lot of time and money for me to do that since I am the only maintainer of the repo. As of now, there is no plan and no timeline yet, but I really appreciate any PR from anyone to implement that particular feature.

Hope that answers your question.
